<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RowingClub.Notifications.Application\RowingClub.Notifications.Application.csproj" />
    <ProjectReference Include="..\RowingClub.Notifications.Domain\RowingClub.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RowingClub.BuildingBlocks.Infrastructure\RowingClub.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RowingClub.BuildingBlocks.Application\RowingClub.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RowingClub.BuildingBlocks.Domain\RowingClub.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
